/**
 * AUTO-GENERATED DATABASE TOOLS
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is automatically generated from ragforge.config.yaml
 * Run 'ragforge generate' to regenerate
 * 
 * For custom tools, use custom-tools.ts instead
 */

import type { RagClient } from '@luciformresearch/ragforge-runtime';
import type { Tool } from '@luciformresearch/ragforge-runtime';

/**
 * Generated tool definitions
 */
export const DATABASE_TOOLS: Tool[] = [
  {
    "name": "query_entities",
    "description": "Query entities from the database with flexible conditions.\n\nAvailable entities: Scope\n\nEntity unique identifiers:\n- Scope: uuid (string)\n\nSearchable/Orderable fields per entity:\n- Scope:\n  * name (string) - \n  * file (string) - \n  * source (string) - \n\nOperators:\n- Comparison: =, !=, >, >=, <, <=\n- String matching:\n  * CONTAINS - Substring match (case-sensitive)\n  * STARTS WITH - Prefix match\n  * ENDS WITH - Suffix match\n  * REGEX - Full regex pattern (e.g., \".*Service$\", \"^Auth.*\")\n  * GLOB - Shell-style wildcards (e.g., \"*Service\", \"Auth*\", \"?ame\")\n    - * matches any sequence of characters\n    - ? matches any single character\n    - [abc] matches any character in brackets\n- List: IN - Check if value is in list\n\nExamples:\n- Find classes: {field: \"type\", operator: \"=\", value: \"class\"}\n- Find auth files: {field: \"file\", operator: \"GLOB\", value: \"*auth*\"}\n- Find services: {field: \"name\", operator: \"REGEX\", value: \".*Service$\"}\n- Find specific scopes: {field: \"name\", operator: \"IN\", value: [\"AuthService\", \"UserService\"]}\n\nYou can ORDER BY any searchable field or computed field (ASC or DESC).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "entity_type": {
          "type": "string",
          "enum": [
            "Scope"
          ],
          "description": "Entity type to query"
        },
        "conditions": {
          "type": "array",
          "description": "WHERE conditions to filter results",
          "items": {
            "type": "object",
            "properties": {
              "field": {
                "type": "string",
                "description": "Field name"
              },
              "operator": {
                "type": "string",
                "enum": [
                  "=",
                  "!=",
                  ">",
                  ">=",
                  "<",
                  "<=",
                  "CONTAINS",
                  "STARTS WITH",
                  "ENDS WITH",
                  "REGEX",
                  "GLOB",
                  "IN"
                ],
                "description": "Comparison operator. Use REGEX for regex patterns, GLOB for shell-style wildcards (* and ?)"
              },
              "value": {
                "description": "Value to compare"
              }
            },
            "required": [
              "field",
              "operator",
              "value"
            ]
          }
        },
        "limit": {
          "type": "number",
          "description": "Max results (default: 10, max: 50)",
          "default": 10
        },
        "order_by": {
          "type": "object",
          "properties": {
            "field": {
              "type": "string"
            },
            "direction": {
              "type": "string",
              "enum": [
                "ASC",
                "DESC"
              ]
            }
          }
        }
      },
      "required": [
        "entity_type"
      ]
    }
  },
  {
    "name": "semantic_search",
    "description": "Semantic search using vector similarity.\n\nAvailable vector indexes:\n- Scope: scopeSourceEmbeddings (field: source)\n\nEntity unique identifiers (for results):\n- Scope: uuid (string)\n\nResults include:\n- Unique identifier (for fetching full entity later)\n- Match score\n- Snippet from matched field\n\nBest for natural language queries about entity content.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "entity_type": {
          "type": "string",
          "enum": [
            "Scope"
          ],
          "description": "Entity type with vector index"
        },
        "query": {
          "type": "string",
          "description": "Natural language search query"
        },
        "top_k": {
          "type": "number",
          "default": 5
        },
        "min_score": {
          "type": "number",
          "default": 0.7
        }
      },
      "required": [
        "entity_type",
        "query"
      ]
    }
  },
  {
    "name": "explore_relationships",
    "description": "Follow relationships between entities.\n\nAvailable relationships (with directions and entity types):\n\n- DEFINED_IN:\n  * Scope -->[DEFINED_IN]--> File\n\n- CONSUMES:\n  * Scope -->[CONSUMES]--> Scope\n\n- HAS_PARENT:\n  * Scope -->[HAS_PARENT]--> Scope\n\n- USES_LIBRARY:\n  * Scope -->[USES_LIBRARY]--> ExternalLibrary\n\n- INHERITS_FROM:\n  * Scope -->[INHERITS_FROM]--> Scope\n\nEntity unique identifiers:\n- Scope: uuid\n\nNavigate the graph to find connected entities.\nUse 'outgoing' for forward direction, 'incoming' for reverse, 'both' for bidirectional.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "start_entity_type": {
          "type": "string",
          "enum": [
            "Scope"
          ]
        },
        "start_conditions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "field": {
                "type": "string"
              },
              "operator": {
                "type": "string"
              },
              "value": {}
            }
          }
        },
        "relationship_type": {
          "type": "string",
          "enum": [
            "DEFINED_IN",
            "CONSUMES",
            "HAS_PARENT",
            "USES_LIBRARY",
            "INHERITS_FROM"
          ]
        },
        "direction": {
          "type": "string",
          "enum": [
            "outgoing",
            "incoming",
            "both"
          ],
          "default": "outgoing"
        },
        "target_entity_type": {
          "type": "string",
          "enum": [
            "Scope"
          ]
        },
        "limit": {
          "type": "number",
          "default": 10
        }
      },
      "required": [
        "start_entity_type",
        "relationship_type"
      ]
    }
  },
  {
    "name": "get_entity_by_id",
    "description": "Get full entity details by unique identifier.\n\nEntity unique identifiers:\n- Scope: uuid (string) - UUID assigned during ingestion\n\nUse this when you have a unique identifier from another query result.\nReturns complete entity with all properties.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "entity_type": {
          "type": "string",
          "enum": [
            "Scope"
          ]
        },
        "id_value": {
          "type": "string",
          "description": "Value of the unique identifier"
        }
      },
      "required": [
        "entity_type",
        "id_value"
      ]
    }
  }
];

/**
 * Attach handlers to database tools
 * @param ragClient - RAG client instance
 */
export function attachDatabaseHandlers(ragClient: RagClient): Map<string, Function> {
  const handlers = new Map<string, Function>();

  // Note: Handler attachment logic would go here
  // This is simplified for now - full implementation in Phase 2

  return handlers;
}
