/**
 * Ingest code from configured source paths
 * Generated by RagForge
 */

import { IncrementalIngestionManager } from '@luciformresearch/ragforge-runtime';
import { createRagClient } from '../client.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

const rag = createRagClient();

console.log('🔄 Starting code ingestion...\n');

const manager = new IncrementalIngestionManager(rag.client);

// Source configuration (from ragforge.config.yaml)
// Note: include/exclude paths are relative to the config file location
const config = {
  type: 'code' as const,
  root: projectRoot,
  include: ["../packages/runtime/src/**/*.ts","../packages/core/src/**/*.ts","../packages/cli/src/**/*.ts"],
  exclude: ["**/node_modules/**","**/dist/**","**/*.test.ts","**/*.spec.ts"],
  adapter: 'typescript' as const,
  track_changes: true
};

try {
  // Parse and ingest (incremental by default)
  const stats = await manager.ingestFromPaths(config, {
    incremental: true,
    verbose: true
  });

  console.log('\n✅ Ingestion complete!');
  console.log(`   Created: ${stats.created}`);
  console.log(`   Updated: ${stats.updated}`);
  console.log(`   Unchanged: ${stats.unchanged}`);
  console.log(`   Deleted: ${stats.deleted}`);

} catch (error) {
  console.error('❌ Ingestion failed:', error);
  process.exit(1);
} finally {
  await rag.close();
}
