# Example: Code Analysis with Field-Level Summarization
#
# This config demonstrates how to enable summarization for code source fields.
# The LLM will generate summaries including improvement suggestions.

name: code-analysis-with-summaries
version: 0.1.0
description: Code analysis with intelligent summarization and improvement suggestions

neo4j:
  uri: bolt://localhost:7687
  username: neo4j
  password: password

# Summarization LLM (can differ from reranking LLM)
summarization_llm:
  provider: gemini
  model: gemini-2.0-flash-exp  # Fast and cheap for summaries
  temperature: 0.3  # Lower temperature for more consistent summaries
  max_tokens: 1000

# Custom or override default strategies (optional)
summarization_strategies:
  # Override the default code_analysis strategy
  code_analysis:
    name: Enhanced Code Analysis
    description: Comprehensive code analysis with security focus
    system_prompt: |
      You are an expert code analyst with focus on security and best practices.

      Analyze code to extract:
      - Purpose and functionality
      - Key operations and algorithms
      - Dependencies and APIs used
      - Programming concepts
      - Security vulnerabilities
      - Performance issues
      - Maintainability concerns

      Your analysis must be:
      - Accurate: Only describe what the code actually does
      - Specific: Use concrete names, APIs, patterns from the code
      - Actionable: Provide implementable suggestions
      - Security-focused: Identify all potential vulnerabilities

    output_schema:
      root: analysis
      fields:
        - name: purpose
          type: string
          description: What the code does (1-2 sentences)
          required: true
        - name: operation
          type: array
          description: Key operations or algorithms
        - name: dependency
          type: array
          description: Important dependencies or APIs
        - name: concept
          type: array
          description: Programming concepts used
        - name: security_issue
          type: array
          description: Security vulnerabilities found
        - name: performance_issue
          type: array
          description: Performance problems identified
        - name: maintainability_issue
          type: array
          description: Code quality and maintainability concerns
        - name: suggestion
          type: array
          description: Specific improvement suggestions
        - name: complexity
          type: string
          description: Overall complexity (simple/moderate/complex/very complex)

    instructions: |
      For security issues, explicitly identify:
      - SQL injection risks
      - XSS vulnerabilities
      - Authentication/authorization flaws
      - Hardcoded secrets
      - Insecure cryptography

      For performance issues, identify:
      - Unnecessary loops or iterations
      - Inefficient algorithms
      - Memory leaks
      - Blocking operations in async code

      Each suggestion must be specific and actionable.

  # Add a custom strategy for documentation
  documentation_quality:
    name: Documentation Quality Analysis
    system_prompt: Analyze code documentation and comments for quality and completeness.
    output_schema:
      root: doc_analysis
      fields:
        - name: has_documentation
          type: boolean
          description: Whether code has documentation
        - name: documentation_quality
          type: string
          description: Quality rating (poor/fair/good/excellent)
        - name: missing_docs
          type: array
          description: What documentation is missing
        - name: improvement
          type: array
          description: How to improve documentation

entities:
  - name: Scope
    description: Code scopes (functions, classes, methods)

    searchable_fields:
      # Name field - no summarization needed
      - name: name
        type: string
        indexed: true

      # Type field - no summarization needed
      - name: type
        type: string
        indexed: true

      # Source code - ENABLE SUMMARIZATION
      - name: source
        type: string
        indexed: false
        description: Source code content
        summarization:
          enabled: true
          strategy: code_analysis  # Use the custom enhanced strategy
          threshold: 300  # Summarize code longer than 300 chars
          cache: true  # Store summaries in Neo4j for reuse
          on_demand: false  # Pre-generate summaries (not on-demand)

          # Extract these fields from the summary
          output_fields:
            - purpose
            - operation
            - concept
            - security_issue
            - performance_issue
            - suggestion
            - complexity

          # Use summary in reranking
          rerank_use: prefer_summary  # Show summary + code excerpt

      # Signature - optional summarization for very long signatures
      - name: signature
        type: string
        indexed: true
        summarization:
          enabled: true
          strategy: text_extraction  # Use built-in text extraction
          threshold: 200
          cache: true
          output_fields:
            - main_topic
            - keyword
          rerank_use: never  # Don't use summary in reranking (signature is already concise)

      # Description field - summarize long descriptions
      - name: description
        type: string
        indexed: false
        summarization:
          enabled: true
          strategy: text_extraction
          threshold: 500
          output_fields:
            - main_topic
            - keyword
            - entity
          rerank_use: always  # Always use summary (original often too long)

    # Vector indexes for semantic search
    vector_indexes:
      - name: source_vector
        field: embedding_source
        source_field: source
        dimension: 768
        similarity: cosine
        provider: gemini
        model: text-embedding-004
        example_query: authentication logic

      - name: name_vector
        field: embedding_name
        source_field: name
        dimension: 768
        similarity: cosine
        provider: gemini
        model: text-embedding-004
        example_query: createUser

    relationships:
      - type: CONSUMES
        direction: outgoing
        target: Scope
        description: Dependencies between scopes
        enrich: true
        enrich_field: consumes

# Embeddings configuration
embeddings:
  provider: gemini
  defaults:
    model: text-embedding-004
    dimension: 768
    similarity: cosine

  entities:
    - entity: Scope
      pipelines:
        - name: source_embeddings
          source: source
          target_property: embedding_source
          batch_size: 100

        - name: name_embeddings
          source: name
          target_property: embedding_name
          batch_size: 100

# Code generation
generation:
  output_dir: ./generated
  language: typescript
  include_tests: true
  include_docs: true
