#!/usr/bin/env node
/**
 * Generate src/version.ts from package.json version
 */
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const pkgPath = join(__dirname, '../package.json');
const versionPath = join(__dirname, '../src/version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));

const content = `// Auto-generated by scripts/generate-version.js
// Do not edit manually
export const VERSION = '${pkg.version}';
`;

writeFileSync(versionPath, content, 'utf-8');
console.log(`✓ Generated version.ts with version ${pkg.version}`);
