/**
 * Generated types for lr-coderag
 * DO NOT EDIT - Generated by RagForge
 */

export interface Scope {
  /** signature of Scope */
  signature?: string;
  /** type of Scope */
  type?: string;
  /** file of Scope */
  file?: string;
  /** uuid of Scope */
  uuid?: string;
  /** name of Scope */
  name?: string;
  /** Vector embedding for semantic search */
  embedding?: number[];
  /** Count of DEFINED_IN relationships */
  definedInCount?: number;
  /** Count of CONSUMES relationships */
  consumesCount?: number;
  /** Count of CONSUMED_BY relationships */
  consumedByCount?: number;
  /** Count of USES_LIBRARY relationships */
  usesLibraryCount?: number;
  /** Count of BELONGS_TO relationships */
  belongsToCount?: number;
}

export interface ScopeFilter {
  signature?: string | {
    equals?: string;
    contains?: string;
    startsWith?: string;
    endsWith?: string;
    in?: string[];
  };
  type?: string | {
    equals?: string;
    contains?: string;
    startsWith?: string;
    endsWith?: string;
    in?: string[];
  };
  file?: string | {
    equals?: string;
    contains?: string;
    startsWith?: string;
    endsWith?: string;
    in?: string[];
  };
  uuid?: string | {
    equals?: string;
    contains?: string;
    startsWith?: string;
    endsWith?: string;
    in?: string[];
  };
  name?: string | {
    equals?: string;
    contains?: string;
    startsWith?: string;
    endsWith?: string;
    in?: string[];
  };
}

export interface File {
  /** name of File */
  name?: string;
  /** Count of IN_DIRECTORY relationships */
  inDirectoryCount?: number;
}

export interface FileFilter {
  name?: string | {
    equals?: string;
    contains?: string;
    startsWith?: string;
    endsWith?: string;
    in?: string[];
  };
}

export interface ExternalLibrary {
  /** name of ExternalLibrary */
  name?: string;
}

export interface ExternalLibraryFilter {
  name?: string | {
    equals?: string;
    contains?: string;
    startsWith?: string;
    endsWith?: string;
    in?: string[];
  };
}

export interface Directory {
  /** Count of PARENT_OF relationships */
  parentOfCount?: number;
}

export interface DirectoryFilter {
}

export interface SearchResult<T> {
  /** The entity that matched */
  entity: T;
  
  /** Overall relevance score (0-1) */
  score: number;
  
  /** Score breakdown by strategy */
  scoreBreakdown?: {
    semantic?: number;
    topology?: number;
    custom?: Record<string, number>;
  };
  
  /** Additional context */
  context?: {
    /** Related entities (if expand was used) */
    related?: any[];
    
    /** Text snippet highlighting match */
    snippet?: string;
  };
}

export interface QueryBuilder<T> {
  /** Filter by field values */
  where(filter: Partial<T>): QueryBuilder<T>;
  
  /** Semantic search by text */
  semantic(query: string, options?: { topK?: number }): QueryBuilder<T>;
  
  /** Expand to related entities via relationships */
  expand(relType: string, options?: { depth?: number }): QueryBuilder<T>;
  
  /** Apply reranking strategy */
  rerank(strategy: RerankingStrategy): QueryBuilder<T>;
  
  /** Limit number of results */
  limit(n: number): QueryBuilder<T>;
  
  /** Skip first n results */
  offset(n: number): QueryBuilder<T>;
  
  /** Execute query and return results */
  execute(): Promise<SearchResult<T>[]>;
  
  /** Explain query plan (for debugging) */
  explain(): Promise<QueryPlan>;
}

export type RerankingStrategy =
  | 'topology-centrality'
  | 'code-quality'
  | 'recency'
  | { strategy: string; weights?: Record<string, number> };